### ISSUE TITLE
dłuższa lista "next candidates" 

### ISSUE THREAD

**Issue by awujek** [agorzawski/fairtaskassigner#2]
Może się okazać że żadnej z 3 osób na obecnej liście nie ma. I co wtedy? Nikt nie pójdzie....? nie będzie kawy...?

**Comment by agorzawski** [comment]
poki co zawsze mozna zerknac na trzeciego taba 'SignUpBuddy' tam jest cala lista z rankingiem - do ogarniecia na 'oko'

**Comment by agorzawski** [comment]
po [commicie](https://github.com/agorzawski/fairtaskassigner/commit/bfb8c3baf8bbcaeb1b0dfc347f1bf2db2b2f0ab3) do zamkniecia
